name: 'dbt_core'
version: '1.0'
config-version: 2

# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 'dbt-snowflake'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

snapshots:
    +target_schema: snapshots

models:
    dbt_core:
        bronze:
            +docs:
                node_color: "#B5A642"
            +tags: [bronze]
            app_db:
                +schema: bronze_app_db
            gsc:
                +schema: bronze_gsc

        silver:
            +docs:
                node_color: "silver"
            +tags: [silver]
            product:
                +schema: silver_product
        gold:
            +docs:
                node_color: "gold"
            +materialized: |
                {%- if target.name == "prod" -%} table
                {%- else -%} view
                {%- endif -%}
            +tags: [gold]
            product:
                +schema: gold_product