name: 'dbt_core'
version: '1.0'
config-version: 2

# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 'dbt-snowflake'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
asset-paths: ["assets"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

seeds:
    schema: mapping

snapshots:
    +target_schema: snapshots

models:
    materialized: view
    incremental_strategy: "merge"

    dbt_core:
        bronze:
            +docs:
                node_color: "#B5A642"
            +tags: [bronze]
            application_db:
                +schema: bronze_application_db
        silver:
            +docs:
                node_color: "silver"
            +tags: [silver]
            dim:
                +schema: silver_dim
        gold:
            +docs:
                node_color: "gold"
            +materialized: |
                {%- if target.name == "prod" -%} table
                {%- else -%} view
                {%- endif -%}
            +tags: [gold]
            monthly_reports:
                +schema: gold_monthly_reports